name: Build and Deploy

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Test (if tests exist)
      run: |
        if [ -d "Tests" ] || [ -f "*.Tests.csproj" ]; then
          dotnet test --no-build --verbosity normal --configuration Release
        else
          echo "No tests found, skipping test step"
        fi
      shell: bash

    - name: Publish
      run: dotnet publish --no-build --configuration Release --output ./publish

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: webhs-app
        path: ./publish

  docker:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: docker build -t webhs:latest .

    - name: Save Docker image
      run: docker save webhs:latest | gzip > webhs-docker.tar.gz

    - name: Upload Docker artifact
      uses: actions/upload-artifact@v4
      with:
        name: webhs-docker
        path: webhs-docker.tar.gz
